module.exports = [
    {
        id: 276537,
        name: 'Lafortune Park',
        url: 'https://www.singletracks.com/bike-trails/lafortune-park/',
        length: '10.0',
        description: 'The trail is a mix of single tracks that run off of a paved rail system.  Lots of climbs and off course some good down hills.  Trail has seen a lot of new development in the last year or so and is really turning into a great ride.\r\n' +
            '\r\n' +
            'Excellent for a quick afternoon ride\r\n' +
            '\r\n' +
            'The park is also adjacent to a large network of rolling double track dirt trails that run through a hydro field.  These are more used by ATVs but also make for a good long ride',
        directions: 'Two park entrances, one is off of Onondaga drive at the corner of Highway 54 and the other is off of Highway 54',
        city: 'Caledonia',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.10042',
        lon: '-79.99785',
        difficulty: 'Intermediate',
        features: null,
        rating: 2.75,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2017/03/IMG_20170312_153214004-orig-scaled.jpg'
    },
    {
        id: 275826,
        name: 'Tyneside Trail',
        url: 'https://www.singletracks.com/bike-trails/tyneside-trail/',
        length: '9.0',
        description: 'Very simple trail, perfect for anyone very new to mountain biking. Some decent uphills and downhills, as well as a few tight singletrack places. Mostly free of roots, some spots have lots of exposed roots.',
        directions: 'From Upper James, turn right onto Chippewa Rd. East. Follow Chippewa to Tyneside Road. Turn right onto Tyneside Road and follow it for about 500 meters. There is a small parking lot on the left hand side. The trail head is right there.',
        city: 'Mount Hope',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.11478',
        lon: '-79.88018',
        difficulty: 'Intermediate',
        features: 'Night riding allowed',
        rating: 2,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2019/10/6E8ECA80-4C5D-4A81-988D-0D5AD97A614Ejpeg-orig-scaled.jpg'
    },
    {
        id: 282163,
        name: 'Tutlea Heights',
        url: 'https://www.singletracks.com/bike-trails/tutela-heights-2/',
        length: '4.0',
        description: 'Medium length fast from Erie ave technical in some spots. Runs very close to grand river at times try not to fall in. Lots of rocks/roots short sweet climbs and drops. Exit off gilkinson flats by lions park.',
        directions: 'Entrance to trail is at the top of the bridge on cockshutt rd and tutela hights rd and takes you on to the main bike trail by the casino.',
        city: 'Brantford',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.11033',
        lon: '-80.24525',
        difficulty: 'Advanced',
        features: null,
        rating: 3.83,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2016/08/IMG_20160815_162905273_HDR-orig-scaled.jpg'
    },
    {
        id: 285768,
        name: 'Dundas Valley',
        url: 'https://www.singletracks.com/bike-trails/dundas-valley/',
        length: '25.0',
        description: 'Dundas valley rec area is the spot for local riders, hikers, mix of double track and single  track with moderate climbs, and many rolling hills.',
        directions: 'From Burlington take 403 through Hamilton and up the Escarpment. Exit hwy 52 and go North (right). Turn right on Governors Rd. and follow it to the signed entrance about 8km in on your right.',
        city: 'Dundas',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.24539',
        lon: '-79.99592',
        difficulty: 'Beginner',
        features: 'Drinking water, Restrooms',
        rating: 3.67,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2014/10/IMG_20141011_124831-orig.jpg'
    },
    {
        id: 273603,
        name: 'Waterford Heritage Trail',
        url: 'https://www.singletracks.com/bike-trails/waterford-heritage-trail/',
        length: '15.0',
        description: '19 kilometer rail trail extending from Simcoe to Brantford with loops and extensions throughout and at either end. Chip and dust base well maintained and good for all tire sizes.',
        directions: 'Starting at the end of Chuch St W.',
        city: 'Waterford',
        region: 'Ontario',
        country: 'Canada',
        lat: '42.93160',
        lon: '-80.28959',
        difficulty: 'Beginner',
        features: 'Fat biking allowed in winter',
        rating: 3,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2019/09/BD6A6625-0FC5-4DAB-8320-9F623A7516EDjpeg-orig.jpg'
    },
    {
        id: 272605,
        name: 'Heritage Trail',
        url: 'https://www.singletracks.com/bike-trails/heritage-trail-15699/',
        length: '20.0',
        description: 'its an intermediate/advanced trail, there are big rocks and tree roots, and you need a decent bike to ride it, preferably a full suspension. My rocky mountain hard-tail has a bumpy time going over some of the obstacles.',
        directions: 'old dundas road',
        city: 'Hamilton',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.23246',
        lon: '-79.97517',
        difficulty: '',
        features: null,
        rating: 0,
        thumbnail: null
    },
    {
        id: 285956,
        name: 'Iroquois Heights',
        url: 'https://www.singletracks.com/bike-trails/iroquois-hights/',
        length: '7.0',
        description: 'combo trails tricky single track, rail trail, jumps, fallen trees tons of roots awesome ride.',
        directions: '403 to "LINC" East, first exit turn left follow through to second lights turn left follow till parking lot on your right... park and ride.',
        city: 'Ancaster',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.23287',
        lon: '-79.94265',
        difficulty: 'Intermediate',
        features: null,
        rating: 3.79,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2015/05/11174461_10155502664280433_8867787024597548257_o17963-orig.jpg'
    },
    {
        id: 272959,
        name: 'Waterworks Dirt Path',
        url: 'https://www.singletracks.com/bike-trails/waterworks-dirt-path/',
        length: '9.0',
        description: 'In the river flats from Wilkes Dam to trail opening at Morrell St.',
        directions: 'Dirt paths drop off the SC Johnson trail throughout Waterworks Park.',
        city: 'Brantford',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.12673',
        lon: '-80.27519',
        difficulty: '',
        features: null,
        rating: 0,
        thumbnail: null
    },
    {
        id: 285966,
        name: 'Hamilton Brantford Rail Trail',
        url: 'https://www.singletracks.com/bike-trails/hamilton-brantford-rail-trail/',
        length: '50.0',
        description: 'Crushed lime surface, level old rail bed with gentle grades, 100% off-street right-of-way, scenic, no services en route.',
        directions: "Start out at the Trail Centre for Dundas Valley Conservation Area, at 650 Governor's Road Dundas Ontario.",
        city: 'Hamilton',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.24734',
        lon: '-79.85664',
        difficulty: 'Easiest',
        features: null,
        rating: 3.67,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2020/02/1A43CC76-A84A-415C-BBF5-04EBFD7A6D78jpeg-orig.jpg'
    },
    {
        id: 272748,
        name: 'Wilkes Dam River Flats',
        url: 'https://www.singletracks.com/bike-trails/wilkes-dam-river-flats/',
        length: '6.0',
        description: 'Follow the river.',
        directions: 'Main lower trail drops down from SC Johnson trail by water plant and runs various routes to Wilkes Dam.',
        city: 'Brantford',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.13972',
        lon: '-80.27262',
        difficulty: '',
        features: 'Night riding allowed',
        rating: 0,
        thumbnail: null
    },
    {
        id: 281804,
        name: 'Silver Creek Trail',
        url: 'https://www.singletracks.com/bike-trails/silver-creek-trail-6831/',
        length: '1.0',
        description: 'A steep up and downhill trail that goes through forests and fields. Path can be overgrown in some spots',
        directions: 'Off to the left side right before entering Silver Creek bridge pathway off of Ludlow Cr.',
        city: 'Brantford',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.18531',
        lon: '-80.23128',
        difficulty: 'Intermediate',
        features: null,
        rating: 5,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2017/04/IMG_0575-orig-scaled.jpg'
    },
    {
        id: 282878,
        name: "Felker's Falls Trail",
        url: 'https://www.singletracks.com/bike-trails/felkers-falls-trail/',
        length: '5.0',
        description: 'This is a very twisty, technical trail with quite a few log crossings and other obstacles. It is one trail shooting off the Bruce and connecting back to it again.',
        directions: "If you start from the Felker's Falls conservation area parking lot (on Ackland Street) you can follow the paved path to the east until it ends and it will go over a bridge and turn into the Bruce Trail singletrack. Follow that out and wherever the path forks into a Y veer right (not where there are offshoots going STRAIGHT right). After the third Y is where the MTB trail really begins and it hooks back up with the Bruce Trail at the end so you can loop around and do it again if you like!",
        city: 'Hamilton',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.20221',
        lon: '-79.78982',
        difficulty: 'Intermediate',
        features: null,
        rating: 3.8,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2016/05/20160520_171835-orig-scaled.jpg'
    },
    {
        id: 285999,
        name: 'Hardy Rd. Trail',
        url: 'https://www.singletracks.com/bike-trails/hardy-rd-trail/',
        length: '18.0',
        description: 'Good twisty singletrack with not much climbing, fast and flowing with a few sections of rocks and roots.  Can be done as an out and back ride or a lolly-pop loop.  Take some time and explore the few alternate routes in the area.  The trail ends when you get to Powerline Rd. after riding under the 403 highway, turn around and head back to the start.  The entire ride can take between 16-19km depending on the route (out and back or lolly-pop loop).',
        directions: 'From the 403 take the Paris Rd. exit and go south until Hardy Rd., go west onto Hardy Rd.  Look out for a parking area for the trail area on the right side of the road (there is a sign that says trail parking).  Ride from the parking area down Hardy Rd traveling west and keep a look out for a trail going off the road on the left side (south).  The trail goes immediately up a hill, this is the start of Hardy Rd. Trail.',
        city: 'Brantford',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.16206',
        lon: '-80.31308',
        difficulty: 'Intermediate',
        features: null,
        rating: 4.2,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2008/05/2602-1211928925-orig.jpg'
    },
    {
        id: 279885,
        name: 'Christie Lake',
        url: 'https://www.singletracks.com/bike-trails/christie-lake/',
        length: '5.0',
        description: 'A newer trail system with room to grow. Fantastic loops of extremely well groomed single track. IMBA helped here, so the trails are very well constructed. The berms are a real blast to ride. Not overly technical but fast with great flow.',
        directions: '1000 Highway 5 West',
        city: 'Hamilton (Dundas)',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.27507',
        lon: '-80.03476',
        difficulty: 'Intermediate',
        features: null,
        rating: 4.11,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2014/08/IMG_20140803_181909-orig-scaled.jpg'
    },
    {
        id: 286706,
        name: 'Nicks',
        url: 'https://www.singletracks.com/bike-trails/nicks/',
        length: '0.0',
        description: 'prety good dirt jumps we have a transfer a hip transfer a double a single and lot more.',
        directions: 'get to dunnville and head down george street turn on to alder left side its behind the houses.',
        city: 'Dunnville',
        region: 'Ontario',
        country: 'Canada',
        lat: '42.91160',
        lon: '-79.63197',
        difficulty: '',
        features: null,
        rating: 0,
        thumbnail: null
    },
    {
        id: 285767,
        name: 'Rockcliffe Waterdown',
        url: 'https://www.singletracks.com/bike-trails/rockcliffe-waterdown/',
        length: '24.0',
        description: 'This place is almost up or down very little rest also it is rocky and constantly challenges you. Lots of tough obstacles, steep drops and criss crossing trails its best to explore this place and make your own favorite route. There is lots to explore',
        directions: '403 west to Hwy.6 north turn right onto Hwy.5 follow Hwy.5 into Waterdown There are a few entrances to the network visit the bike shop (bicycle works) near the Tim Hortons for directions to the trail heads. ',
        city: 'Waterdown',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.32176',
        lon: '-79.90065',
        difficulty: 'Advanced',
        features: null,
        rating: 3.93,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2012/09/cdv_photo_002-23-orig.jpg'
    },
    {
        id: 281975,
        name: 'Barkers Bush',
        url: 'https://www.singletracks.com/bike-trails/barkers-bush/',
        length: '5.0',
        description: 'Good singletrack, some fun downhill sections, lots of roots.',
        directions: 'To get here you want to go to lions park in Paris.',
        city: 'Paris',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.19242',
        lon: '-80.38894',
        difficulty: 'Intermediate',
        features: null,
        rating: 4.2,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2019/09/mobile-1569684402-orig.jpg'
    },
    {
        id: 279467,
        name: 'Kerncliffe Trail System',
        url: 'https://www.singletracks.com/bike-trails/kerncliffe-trail-system/',
        length: '15.0',
        description: 'Trails are un-marked. West end of network is rocky and technical. East end of network is steep and flows',
        directions: 'Mountainview Road',
        city: 'Hamilton',
        region: 'Ontario',
        country: 'Canada',
        lat: '43.33265',
        lon: '-79.87960',
        difficulty: 'Intermediate',
        features: 'Pump track',
        rating: 4,
        thumbnail: 'https://images.singletracks.com/blog/wp-content/uploads/2016/10/2016-10-10092126-orig-scaled.jpg'
    }
]